name: Security - Docker - Scan

## Run workflow when new changes are proposed
on: [pull_request]

jobs:
  scan:
    name: Scan Docker Images
    ## Workflow runs within an isolated execution environment 
    ## (e.g., fresh Ubuntu 20.04 server)
    runs-on: ubuntu-20.04
    steps:
      ## Allow access to trivy-tutorial Git repo
      - name: Checkout Current Git Repo
        uses: actions/checkout@v2

      - name: Install Trivy
        run: |
          ## Run install script at trivy-tutorial/install.sh
          bash install.sh
      - name: Execute Trivy Scans
        run: |
          bash docker-scan.sh 
